### ISSUE TITLE
.grid__column 의 글자가 가운데가 아니에요

### ISSUE THREAD

**Issue by developer-1px** [Wookshin/wordle-vanilla#12]
.grid__column의 height는 70px인데 line-height가 60px이라서 조금 틀어져서 보여요.
가운데 정렬을 하실꺼라면 display:flex; align-items:center; justify-content: center 나
display:flex 부모에 자식 커텐츠에 margin:auto를 추천드려요 :)

**Comment by Wookshin** [comment]
반영했습니다! 리뷰 감사해요 :D
